---
title: "In Class 7"
author: "Ashton Pallottini"
date: "11/13/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Reading the data set
DATA=read.table('wages.txt',header=T,stringsAsFactors=F)

## model

model='Wage~Education+South+Black+Hispanic+Sex+Married+Experience+Union'  
fm0=lm(model,data=DATA)
summary(fm0)
# Pediction equation
ED=6:18
Z=cbind(1,ED,0,0,0,0,0,4,0) # male, north, not married, non-union, white, 4 yr of experience
head(Z)
yHat=Z%*%coef(fm0)
```

```{r}
n <- nrow(DATA)
yhats <- matrix(nrow = 5000, ncol = 13)
for(i in 1:5000){
  tmp <- sample(1:n, size = n, replace = TRUE)
  tmpDATA <- DATA[tmp,]
  fm <- lm(model, data = tmpDATA)
  yHat.tmp <- Z%*%coef(fm)
  yhats[i,] <- yHat.tmp
}

centers <- yHat
std.errs <- apply(yhats, 2, sd)
t.star <- qt(.975, df = (n - 9))

lower.bounds <- centers - t.star*std.errs
upper.bounds <- centers + t.star*std.errs

ints <- cbind(lower.bounds, upper.bounds)
rownames(ints) <- 6:18
ints #95% CIs

plot(yHat~ED,type='o',col=4)
lines(x = ED, y = lower.bounds)
lines(x = ED, y = upper.bounds)
```



