---
title: "In Class 3"
author: "Ashton Pallottini"
date: "9/25/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls())

library(MASS)
```

###Number 1

```{r}
our.ranks <- as.data.frame(matrix(nrow = 100, ncol = 1000))
```


```{r}
set.seed(12345)

for(j in 1:100){
  p <- 1000
  n <- 200
  rho <- .5
  
  e <- rnorm(n, 0, 1)
  Sigma <- matrix(nrow = p, ncol = p)
  
  for(i in 1:p){
    Sigma[i,i] <- 1
  }
  Sigma[is.na(Sigma)] <- rho
  
  X <- mvrnorm(n = n, mu = rep(0,1000), Sigma = Sigma)
  
  Y <- 5*X[,1] + 5*X[,2] +5*X[,3] + e
  
  our.coef <- rep(0,1000)
  for(i in 1:p){
    reg.i <- lm(Y~X[,i])
    coef.i <- reg.i$coefficients[2]
    our.coef[i] <- abs(coef.i)
  }
  our.ranks[j,] <- rank(-our.coef)
}
```


```{r}
mean.ranks <- colSums(our.ranks)/1000
mean.ranks.ranked <- rank(mean.ranks)
sort(mean.ranks.ranked)[1:10]
```

The top ten variables, in order of highest average rank, are listed above.

###Number 2

```{r}
our.ranks.2 <- as.data.frame(matrix(nrow = 100, ncol = 1000))
```


```{r}
set.seed(54321)

for(j in 1:100){
  p <- 1000
  n <- 200
  rho <- .5
  
  e <- rnorm(n, 0, 1)
  Sigma <- matrix(nrow = p, ncol = p)
  
  for(i in 1:p){
    Sigma[i,i] <- 1
  }
  Sigma[is.na(Sigma)] <- rho
  
  X <- mvrnorm(n = n, mu = rep(0,1000), Sigma = Sigma)
  
  Y <- 3*X[,1] + 3*X[,2] +3*X[,3] + 3*X[,4] + 3*X[,5] - 7.5*X[,6] + e
  
  our.coef <- rep(0,1000)
  for(i in 1:p){
    reg.i <- lm(Y~X[,i])
    coef.i <- reg.i$coefficients[2]
    our.coef[i] <- abs(coef.i)
  }
  our.ranks.2[j,] <- rank(-our.coef)
}
```


```{r}
mean.ranks <- colSums(our.ranks.2)/1000
mean.ranks.ranked <- rank(mean.ranks)
sort(mean.ranks.ranked)[1:10]
```

The top ten variables, in order of highest average rank, are listed above. X6 is not included among these.

```{r}
set.seed(345)
our.ranks.3 <- as.data.frame(matrix(nrow = 99, ncol = 1000))

for(j in 1:99){
  p <- 1000
  n <- 200
  rho <- .5
  
  e <- rnorm(n, 0, 1)
  Sigma <- matrix(nrow = p, ncol = p)
  
  for(i in 1:p){
    Sigma[i,i] <- 1
  }
  Sigma[is.na(Sigma)] <- rho
  
  X <- mvrnorm(n = n, mu = rep(0,1000), Sigma = Sigma)
  
  Y <- 3*X[,1] + 3*X[,2] +3*X[,3] + 3*X[,4] + 3*X[,5] - 7.5*X[,6] + e

  our.coef.3 <- rep(0,1000)
  our.coef.3[1] <- NA
  for(i in 2:p){
    reg.i <- lm(Y~X[,i]+X[,1])
    coef.i <- reg.i$coefficients[2]
    our.coef[i] <- abs(coef.i)
  }
  our.ranks.3[j,] <- rank(-our.coef)
}
```

```{r}
mean.ranks <- colSums(our.ranks.3)/1000
mean.ranks.ranked <- rank(mean.ranks)
sort(mean.ranks.ranked)[1:10]
```

The top ten variables, in order of highest average rank, are listed above. X6 is included among these.
